### PR TITLE
Bms monitoring

### PR DESCRIPTION
**Pull request by Tik-Hakobyan**

### CODE REVIEW

**Comment by mihirnimgade** [comment]
Before you merge this in you're gonna wanna remove the `environment` folder you committed since that should stay local to your computer and isn't meant to be checked in to version control. Also remove the extra `output.txt` files.

**Comment by ishanjoshi23** [comment]
Thanks, Mihir. Will keep that in mind

**Comment by ishanjoshi23** [comment]
TODO before merge:
* Add command line option to specify daybreak or brightside for selecting DBC (Ishan)
* Add documentation on how to connect PCAN using offline mode (Tigran)
* Add logging (with command line option) to save all messages to a json logfile (log files should not tracked by git) (Ishan)

**Comment by ishanjoshi23** [comment]
Rebased the branch on main. Merging

**Review by ishanjoshi23 — APPROVED** [review]

**Comment by mihirnimgade** [comment]
@ishanjoshi23 Hey, before this is merged, can we bring back `daybreak.dbc`? Don't really see a point in deleting it.

**Comment by ishanjoshi23** [comment]
@mihirnimgade Yep, I added it back. needed for the unit tests to pass.

**Pull request merged**
